version: '3.8'

services:
  spring:
    image: tangpoo/troller:1.0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"